
pipeline {
    
    agent { label 'node-1' }
    environment{
        SONAR_HOME = tool "Sonar-Scaner"
    }
    stages {
        
        stage("Code"){
            steps{
                git url: "https://github.com/vaibhav-devops17/kanban-todo-project.git" , branch: "master"
                echo "Repository Code Cloned Successfully"
            }
        }
        stage("SonarQube Analysis"){
            steps{
               withSonarQubeEnv("Sonar-Scaner"){
                   sh "$SONAR_HOME/bin/sonar-scanner -Dsonar.projectName=kanban-todo -Dsonar.projectKey=kanban-todo -X"
               }
            }
        }
        stage("SonarQube Quality Gates"){
            steps{
               timeout(time: 1, unit: "MINUTES"){
                   waitForQualityGate abortPipeline: false
               }
            }
        }
        
        //stage("OWASP"){
            //steps{
                //dependencyCheck additionalArguments: '--scan ./', odcInstallation: 'OWASP'
                //dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            //}
        //}
        
        stage("Build & Test"){
            steps{
                sh 'docker build -t kanban-todo-app:latest .'
                echo "Code Built Successfully"
            }
        }
        stage("Trivy"){
            steps{
                sh "trivy image kanban-todo-app"
            }
        }
        stage("Push to Private Docker Hub Repo"){
            steps{
                withCredentials([usernamePassword(credentialsId:"DockerHubCreds",usernameVariable:"DockerUser",passwordVariable:"DockerPass")]){
                sh "docker login -u ${env.DockerUser} -p ${env.DockerPass}"
                sh "docker tag kanban-todo-app:latest ${env.DockerUser}/kanban-todo-app:latest"
                sh "docker push ${env.DockerUser}/kanban-todo-app:latest"
                }
                
            }
        }
        stage("Deploy"){
            steps{
                sh "docker-compose down && docker-compose up -d"
                echo "App Deployed Successfully"
            }
        }
    }
}
